## Either use source("./PrepareData.R") or below code

# Download the zip file by the provided URL and unzip it
dataUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
download.file(dataUrl, "./NEI_data.zip", method = "curl")
unzip("./NEI_data.zip")

# Read data
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")

# Subsetting the data by chooseing data from Baltimore and LA only
BLNEI <- subset(NEI, fips == "24510" | fips == "06037")

# After some search around, I found it's no easy to determin which source is motor
# vehicle and I chose to find "motor" or "vehicle" in the EI.Sector column of SCC
SCCMotor <- subset(SCC, grepl("motor|vehicle", EI.Sector, ignore.case = T))
SCCMotor$SCC <- as.character(SCCMotor$SCC)

# Subset the data frame by choosing only the related columns
BLNEIMotor <- subset(BLNEI, BLNEI$SCC %in% SCCMotor$SCC, select = c("fips", "Emissions", "year"))
# Convert the fips column to factor class and assign levels, then rename the column name to "city"
BLNEIMotor$fips <- as.factor(BLNEIMotor$fips)
levels(BLNEIMotor$fips) <- c("LA", "BAL")
names(BLNEIMotor)[1] <- "city"

if (require(dplyr) == F) {
        install.packages("dplyr")
}
library(dplyr)

# Use the group_by function to perform the grouping by city and year
grpBLNEIMotor <- group_by(BLNEIMotor, city, year)
sumBLNEIMotor <- summarise_each(grpBLNEIMotor, funs(sum))

if (require(ggplot2) == F) {
        install.packages("ggplot2")
}
library(ggplot2)

# The city column has been converted to factor, so use ggplot to put the trends of both
# cities in one plot to show the comparison. I used two smooth functions here. One is a
# smooth line to connect all data points, the other is a straight blue line generated by
# lm function. The absolute value of LA and BAL emissions differ a lot, hence I used facet
# and free scale here.
ggplot(data = sumBLNEIMotor, aes(x = year, y = Emissions, colour = city, xlab = "Year")) +
        geom_point() + geom_smooth() + geom_smooth(method = "lm", col = "blue") +
        xlab("Year") + ylab("Total PM2.5 Emissions (tons)") +
        facet_wrap(~city, scales = "free")
# In terms of the absolute value, LA has greater changes over the time. But considering the
# relative value, BAL has greater changes.

# Save the plot to a png file named "plot6.png"
dev.copy(png, width = 800, unit = "px", file = "plot6.png")
dev.off()
